config/routes.rb
Rails.application.routes.draw do

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end

  root 'posts#index'

  get ':user_name', to: 'profiles#show', as: :profile

  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	acts_as_votable

	belongs_to :user

	has_many :comments, dependent: :destroy

	validates :user_id, presence: true
	validates :image, presence: true
	validates :caption, length: { minimum: 3, maximum: 300 }

	has_attached_file :image
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :comments, dependent: :destroy

	has_many :posts, dependent: :destroy

	validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  	has_attached_file :avatar, styles: { medium: '152x152#' }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_post

	def index
		@comments = @post.comments.order("created_at ASC")

		respond_to do |format|
			format.html { render layout: !request.xhr? }
		end
	end

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		else
			flash[:alert] = "Check the comment form, something went horribly wrong."
			render root_path
		end
	end

	def destroy
		@comment = @post.comments.find(params[:id])

		if @comment.user_id == current_user.id
			@comment.delete
			respond_to do |format|
				format.html { redirect_to root_path }
			end
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_post
		@post = Post.find(params[:post_id])
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
	before_action :authenticate_user!
	before_action :owned_post, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all.order('created_at DESC').page params[:page]
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			flash[:success] = "Your post has been created!"
			redirect_to posts_path
		else
			flash.now[:alert] = "Your new post couldn't be created! Please check the form."
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Post updated."
			redirect_to posts_path
		else
			flash.now[:alert] = "Update failed. Please check the form."
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def like
		if @post.liked_by current_user
			respond_to do |format|
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	private

	def post_params
		params.require(:post).permit(:image, :caption)
	end

	def set_post
		@post = Post.find(params[:id])
	end

	def owned_post
		unless current_user == @post.user
			flash[:alert] = "That post doesn't belong to you!"
			redirect_to root_path
		end
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!
	before_action :owned_profile, only: [:edit, :update]
  before_action :set_user

  def show
    @user = User.find_by(user_name: params[:user_name])
  	@posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end

  def update
  	@user = User.find_by(user_name: params[:user_name])
  	if @user.update(profile_params)
  		flash[:success] =  'Your profile has been update.'
  		redirect_to profile_path(@user.user_name)
  	else
  		@user.errors.full_messages
  		flash[:error] = @user.errors.full_messages
  		render :edit
  	end
  end

  	def edit
		@user = User.find_by(user_name: params[:user_name])
	end

  private

  def profile_params
  	params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
  	@user = User.find_by(user_name: params[:user_name])
  	unless current_user == @user
  		flash[:alert] = "That profile doesn't belong to you!"
  		redirect_to root_path
  	end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
	end
		
end

app/helpers/application.rb
def alert_for(flash_type)
	{ success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert_info'}
	[flash_type.to_sym] || flash_type.to_s
end

app/helpers/application_helper.rb
module ApplicationHelper

	def form_image_select(post)
      return image_tag post.image.url, id: 'image-preview', class: 'img-responsive' if post.image.exists? image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
	end

	def profile_avatar_select(user)
		return image_tag user.avatar.url, id: 'image-preview', class: 'img-responsive img-circle profile-image' if user.avatar.exists? image_tag 'default-avatar.jpg', id: 'image-preview', class: 'img-responsive img-circle profile-image'
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	# Our new helper method
	def likers_of(post)
		# votes variable is set to the likes by users.
		votes = post.votes_for.up.by_type(User)
		# set user_names variable as an empty array
		user_names = []
		# unless there are no likes, continue below.
		unless votes.blank?
			# iterate through the voters of each vote (the users who liked the post)
			votes.voters.each do |voter|
				# add the user_name as a link to the array
				user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
			end
			# present the array as a nice sentence using the as_sentence method and also make it usable within our html. Then call the like_plural method with the votes variable we set earlier as the argument.
			user_names.to_sentence.html_safe + like_plural(votes)
		end
	end

	private
	# If we more than one like for a post, use ' like this'
	def like_plural(votes)
		return ' like this' if votes.count > 1
		# Otherwise, return ' likes this'
		'likes this'
		
	end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
  <div class="user-name">
    <%= link_to comment.user.user_name, profile_path(comment.user.user_name) %>
  <% if comment.user %>
    <%= comment.user.user_name %>
  <% end %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm:"Are you sure?" }, remote: true do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render@post.comments, post: @post, comment: @comment %>");

app/views/comments/index.html.erb
<%= render @comments, post: @post %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert] %>
    <% end %>
  </div>
  <div class="navbar-header">
    <button class="navbar-toggle collapsed">{"data-target" => "#bs-navbar-collapsed-1", "data-toggle" => "collapse", type: "button:}
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand">
      <%= link_to "Photogram", root_path %>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <%= link_to "New Post", new_post_path %>
      </li>
      <li>
        	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </li>
      <% else %>
	    <li>
    		<%= link_to "Login", new_user_session_path %>
  	  </li>
      <li>
        <%= link_to "Register", new_user_registration_path %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Photogram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= image_tag 'placeholder.jpg', id: 'image-preview', class 'img-responsive' %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row"></div>
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image:</h4>
              <%= f.input :image, label: false, input_html: {onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>P
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div class="likes">
  <%= likers_of post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="user-name">
      <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
    </div>
    <div class="time-ago">
      <%= time_ago_in_words post.created_at %>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url, class: 'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
    <%= render 'posts/likes', post: post %>
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
          </div>
          <%= post.caption %>
        </div>
        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments.any? %>
          <div class="paginator" id="#comments-paginator-<%= post.id %>">
          <% unless post.comments.count <= 4 %>
            <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
          <% end %>
          </div>
          <%= render post.comments.last(4), post: post %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="comment-like-form row">
        <div class="col-sm-1">
        <%= link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "glyphicon glyphicon-heart-empty" %>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image.url %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post|  %>
    <%= render 'post', post: post %>
    <%= paginate @posts %>
    <div class="post">
      <div class="post-head">
        <div class="thumb-img">
          <div class="user-name">
            <%= post.user.user_name %>
          </div>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url, class: 'img-responsive'), post_path(post)  %>
      </div>
      <div class="post-bottom">
        <div class="caption">
          <div class="user-name">
            <%= post.user.user_name  %>
          </div>
          <%= post.caption  %>
          <div id="posts">
          </div>
          <div class="text-center" id="paginator">
            <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<% escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove();}

app/views/posts/new.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>

<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button' %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
      </div>
    </div>
  </div>
</div>
<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>